apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  type: NodePort
  ports:
    - name: apache
      port: 80
      targetPort: 80
      nodePort: 30031
  selector:
    app: haproxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  serviceName: haproxy
  replicas: 3
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy
        imagePullPolicy: Never
        command: ["sh", "/tmp/entrypoint.sh"]
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

