apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: nfs-server
        image: nfs
        imagePullPolicy: Never
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/www/nfs"
            name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  type: NodePort
  ports:
    - name: apache
      port: 80
      targetPort: 80
      nodePort: 30003
    - name: nfs
      port: 2049
      nodePort: 30004
    - name: mountd
      port: 20048
      nodePort: 30005
    - name: rpcbind
      port: 111
      nodePort: 30006
  selector:
    role: nfs-server
